apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: postgres-ha
  namespace: databases
  labels:
    app: postgres-ha
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      cnpg.io/cluster: postgres-ha
  podMetricsEndpoints:
  - port: metrics
    interval: 30s